package obeli-sk:version-monitor;

interface repo-monitor-action {
    record merge-request {
        number: u64,
        head: string,
    }

    variant repo-action {
        run-gha,
        merge(merge-request),
    }

    action: func() -> result<repo-action, string>;
}

world repo-monitor-action-world {
    export repo-monitor-action;
}
