package obeli-sk:version-monitor;

interface repo-monitor-state {
    record pull-request {
        number: u64,
        html-url: string,
        state: string,
        checks-state: option<string>,
        head-sha: option<string>,
    }

    record repo-state {
        repo: string,
        version: option<string>,
        pull-request: option<pull-request>,
    }

    state: func(event-id: string) -> result<repo-state, string>;
}

world repo-monitor-state-world {
    export repo-monitor-state;
}
